twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_title: '%app.name%'
        app_subtitle: '%app.longName%'
        app_version: '%app.version%'

    form_themes: ['bootstrap_4_layout.html.twig']
when@test:
    twig:
        strict_variables: true
